spring: 
    application: 
        name: PRODUCT-SERVICE
server: 
    port: 9090
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance: 
        hostname: localhost
category: 
    api: 
        url: http://localhost:8080/categories
